function Hd = filter_rectangular
%FILTER_RECTANGULAR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and Signal Processing Toolbox 8.5.
% Generated on: 18-Feb-2021 12:19:53

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 40;  % Sampling Frequency

N    = 16;       % Order
Fc   = 2;        % Cutoff Frequency
flag = 'scale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = rectwin(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
